version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
      - ./llm:/llm
    ports:
      - "11434:11434"
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - private_network

  deceptify_client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      ollama:
        condition: service_healthy
    restart: always
    command: [ "python3", "login.py" ]
    ports:
      - "5000:5000"
    volumes:
      - ./llm:/llm
    networks:
      - private_network

volumes:
  ollama:

networks:
  private_network:
    driver: bridge